apiVersion: v1
kind: ServiceAccount
metadata:
  name: echo-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-service
  template:
    metadata:
      labels:
        app: echo-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: echo-service
      containers:
      - name: echo
        image: python:3.9-slim
        command: ["python", "-m", "http.server", "5000"]
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: echo-service
spec:
  selector:
    app: echo-service
  ports:
  - port: 5000
    targetPort: 5000